spring.application.name=notification-service
server.port=8086

# MongoDB
spring.data.mongodb.uri=mongodb+srv://admin:adminadmin@cluster0.rpejk7l.mongodb.net/notificationdb?retryWrites=true&w=majority&appName=Cluster0

# JWT (shared secret — must match user-service)
jwt.secret=foodpanda-user-service-super-secret-key-2024-change-in-production
jwt.expiration=3600000
