spring.application.name=order-service
server.port=8084

# MongoDB
spring.data.mongodb.uri=mongodb+srv://admin:adminadmin@cluster0.rpejk7l.mongodb.net/orderdb?retryWrites=true&w=majority&appName=Cluster0

# JWT (shared secret — must match user-service)
jwt.secret=foodpanda-user-service-super-secret-key-2024-change-in-production
jwt.expiration=3600000

# Internal service URLs
service.user.url=http://localhost:8081
service.restaurant.url=http://localhost:8082
service.delivery.url=http://localhost:8085
service.notification.url=http://localhost:8086

# Eureka Service Registry
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
