spring.application.name=delivery-dispatch-service
server.port=8087

# MongoDB
spring.data.mongodb.uri=mongodb+srv://admin:adminadmin@cluster0.rpejk7l.mongodb.net/deliverydb?retryWrites=true&w=majority&appName=Cluster0

# JWT (shared secret — must match user-service)
jwt.secret=foodpanda-user-service-super-secret-key-2024-change-in-production
jwt.expiration=3600000

# Internal service URLs
service.order.url=http://localhost:8086
service.notification.url=http://localhost:8085
