spring.application.name=restaurant-catalog-service
server.port=8082

# MongoDB
spring.data.mongodb.uri=mongodb+srv://admin:adminadmin@cluster0.rpejk7l.mongodb.net/catalogdb?retryWrites=true&w=majority&appName=Cluster0

# JWT (shared secret — must match user-service)
jwt.secret=foodpanda-user-service-super-secret-key-2024-change-in-production
jwt.expiration=3600000

# Eureka Service Registry
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
